### ISSUE TITLE
Unable to send files in MUCs

### ISSUE THREAD

**Issue by likeadragonmaid** [skrivame/Skriva#11]
Something broke between 7a661ffc535c003b4b1e7d7e759f38af903e8ba1 and d3b4384db5d3cbe3728f3f65c233fb543ff187e2 which caused attach file button in MUCs to disappear. Also when you share a file from any other app to skriva, MUCs don't show up.

**Comment by ReyKoxha** [comment]
Hello shouko,

first of all sorry for my late response.
I made a mistake here.
Back then I saw that Daniel disabled the upload and kept my settings set to "false".
However, for some reason I must have thought that my release version had the wrong value set.

Therefore, I apologize and hope this didn't cause too much of an issue.

I will release a new version to the Play Store ASAP.
Going to close the ticket once thats done.

Greetings,

Rey
