### ISSUE TITLE
Getting errors while building

### ISSUE THREAD

**Issue by likeadragonmaid** [skrivame/Skriva#12]
Build Variant: skrivaFreeCompatDebug
File: Skriva/src/main/java/me/skriva/ceph/services
LN: 761: mPushManagementService.unregisterChannel(account, hash);
error: cannot find symbol method unregisterChannel(Account,String)

LN: 2653: mPushManagementService.disablePushOnServer(conversation);
error: cannot find symbol method disablePushOnServer(Conversation)

Can you please help me to fix these errors?

**Comment by ReyKoxha** [comment]
Hello shouko,

I made a bunch of mistakes in those commits.
However, this time I made sure everything was inherited properly.

Greetings,

Rey
