### ISSUE TITLE
Make more clear what advantages over Conversations are.

### ISSUE THREAD

**Issue by free5lot** [skrivame/Skriva#8]
Make more clear what advantages over Conversations are.
It's not obvious from the web site, nor github.
Some key points could motivate users to start using Skriva.

**Comment by ReyKoxha** [comment]
Hello @free5lot.

Thanks for opening the ticket.
You are right about this and it was on my todo list to update screenshots and the text on the site soon.

However, I would like to make clear that Skriva is not supposed to compete with or even replace Conversations.

This fork is targeted at people, who have never used a XMPP client before and simply seek for a straight forward solution to benefit from OMEMO and an "open" service in general.
