### ISSUE TITLE
Unable to login using an existing account

### ISSUE THREAD

**Issue by likeadragonmaid** [skrivame/Skriva#9]
When I try to login using an existing account at 404.city it says that it is not a valid username. I am using latest build from Google Play. I am already being able to use the same account on conversations.

**Comment by ReyKoxha** [comment]
The app is locked to skriva.me.

**Comment by likeadragonmaid** [comment]
Will it be ever unlocked? Also make it clear in website, google play and read me that this app is locked to skriva.me only.

**Comment by ReyKoxha** [comment]
You are absolutely right about that.
Going to make things more clear for normal users.

If you wish to use your own domain you would have to edit this file:
https://github.com/skrivame/Skriva/blob/master/src/main/java/me/skriva/ceph/Config.java
